### ISSUE TITLE
Improve stack trace reporting

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#105]
> Need to try and figure out how to get better stack traces. Sometimes in the error logs you only get a Container Error and its really unhelpful

That's right ! 

I put here a contribution related to the improvement of the stack trace https://github.com/MasoniteFramework/logging/pull/6

**Comment by josephmancuso** [comment]
For the issue relating to M4, This is fixed. I removed a location where we were catching an exception and throwing a new exception which completely deleted the relevant stack trace. I did this for a reason but now I can't figure out why I did it ... so just have to monitor that
