### ISSUE TITLE
Improve access to url helper

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#114]
I would like to use `UrlHelper(self.application).url()` helper outside of a view, it would be good to be able to do:
```python
from masonite.helpers..... import url

url(..)
```
instead of writing `UrlHelper(self.application).url()`

how should we do this ? Facade ? or just:

```python

# somewhere in helpers module

def url(path):
    from wsgi import application
    return UrlHelper(application).url(path)
```

**Comment by josephmancuso** [comment]
facades? lol I think the answer to all of our questions from here on out is to use Facades 🤣

**Comment by josephmancuso** [comment]
do something like:

```python
# helpers/__init__.py file somewhere
from ..facades import URLFacade as url
```

and then you would do:

```
from masonite.helpers import url

def show(self):
    url().something()
```

?

**Comment by josephmancuso** [comment]
no idea if that works lol

**Comment by girardinsamuel** [comment]
It should ! But for this to work, the UrlHelper must be added to the container => For now it's not... is it okay to add it ?

**Comment by josephmancuso** [comment]
that's a good point. Yeah we can add anything we want to the container
