### ISSUE TITLE
Session data is not persisted between subsequent requests

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#119]
I am not talking about flash messages but about session data added with `set()` method.
When doing `request.app.make("session").set("test", "hello")` in a view and getting an other view in the next request
`request.app.make("session").all()` is empty...

It's like every session data is treated as flash messages. I guess the reason is that session is built from cookies and that session is not correctly "hydrated" from the cookies now they are in request and response ??

**Comment by girardinsamuel** [comment]
With a deep look what happens is the following 😉 :
- I set session data  in a view with `request.app.make("session").set("test", "hello")` => a cookie `s_test` will be added to response
- I can see this cookie in devtools and I can display session data in the view
- I navigate to an other view, `s_test` cookie is sent through request this time
- When fetching again session data with `request.app.make("session").get("test")` it will look into cookie in response but now `s_test` cookie is in request and not yet in response

So what should we do ? Transfer request cookie to response cookie each time in the lifecycle ?

**Comment by josephmancuso** [comment]
@girardinsamuel Some of this session stuff is fixed in #63

**Comment by josephmancuso** [comment]
One thing we still need to figure out is how to get templates to render error messages

**Comment by girardinsamuel** [comment]
I guess a helper `errors` could fetch flash messages with key `errors` and with could have stuff like, errors() or errors().first().

**Comment by josephmancuso** [comment]
Fixed in #120
