### ISSUE TITLE
Middleware can no longer accept arguments

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#123]
Somewhere along the way we missed the requirement that middleware should accept values like `auth:parameter`. This is used for route middleware

**Comment by girardinsamuel** [comment]
Could you add an example of usage of a middleware with such an argument ?

**Comment by josephmancuso** [comment]
@girardinsamuel 

```python
ROUTES = [
    Route.get(..).middleware('middleware:argument1,argument2')
]
```

**Comment by josephmancuso** [comment]
V3 had this functionality. Only place we used it internally was to set the guard (`guard:api`) which changes the guard for that route
