### ISSUE TITLE
When do you expect to release the official version of masonite4?

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite4#130]
I like this framework very much and look forward to the official release.

**Comment by goophps** [comment]
I am really looking forward to it. I have come here every day recently.

**Comment by Marlysson** [comment]
@goophps Able the notifications for all of this repository. You'll keep updated about some news.

**Comment by goophps** [comment]
I come to see it every day

**Comment by goophps** [comment]
I am looking forward

**Comment by goophps** [comment]
It seems that there hasn't been any movement lately

**Comment by girardinsamuel** [comment]
Both @josephmancuso  and I have been quite occupied on some urgent business. We are looking forward to release it too, as soon as possible !

**Comment by girardinsamuel** [comment]
@goophps I am slowly getting back to Masonite 🚀 ! We will keep you posted when we have decided of a release date !
