### ISSUE TITLE
code in providers boot() not called during the tests

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#153]
That's not a big deal as more often it is used as part of the lifecycle request but I can see some use cases:
- during unit tests
- in somme console commands

For example, I was trying to test View facade to render a view. We might have to do this in a console command or to assess behaviour in a unit test, and here as boot() methods of providers are not called, some stuff are not shared in the view that are usually shared (session, request,...) and that can lead to errors.

Should be boot providers during tests if we are not making a request ?
What's your opinon on that ?

**Comment by josephmancuso** [comment]
So I would think it should call the boot method as it normally would during a real request
