### ISSUE TITLE
Craft Serve Error on fresh install

### ISSUE THREAD

**Issue by alitokmakci** [MasoniteFramework/masonite4#159]
File "/Users/xxx/xxx/Kernel.py", line 95, in register_storage
    storage = StorageCapsule(self.application.base_path)
TypeError: __init__() takes 1 positional argument but 2 were given

Env: MACOS, Python3.9.5

What did I ?
```
python -m venv venv
source venv/bin/activate
pip install masonite==4.0.0b1
start project .
python craft serve

```
I tried also v4.0.0b1 but still same error. I am not getting any error on v3

**Comment by josephmancuso** [comment]
Do you have a valid key set in your .env file? or does it says something like `APP_KEY=your-secret-key`

**Comment by alitokmakci** [comment]
Yes it was the laravel's cookies causing this issue ty for your intereset! Happy coding! Love your work!

**Comment by girardinsamuel** [comment]
I don't know yet, I have encoutered the same issue...and it's quite annoying when dealing with multiple projects...
