### ISSUE TITLE
When crafting a project and starting we always get an InvalidCSRFToken exception

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#167]
It's quite annoying and not a good user experience especially for new comers..it's a bit worrying to already see an error after starting a brand new project.

Of course if we delete the cookies related to CSRF token in the browser the error's gone...

How to address this ?

There is no such a problem in Django

**Comment by josephmancuso** [comment]
I changed this to just not decrypt the token if it can't so this should be solved now
