### ISSUE TITLE
Add Gates and Policies docs

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#174]

**Comment by josephmancuso** [comment]
@girardinsamuel Anyway you can you add the documentation for the gates and policies feature you made?

**Comment by josephmancuso** [comment]
@girardinsamuel it can be done on the authentication docs https://docs.masoniteproject.com/v/v4.0/features/authentication#gates-and-policies

**Comment by girardinsamuel** [comment]
Do you think we should create a authorization feature instead ? To avoid a long page and also to better split the two concepts ?

**Comment by josephmancuso** [comment]
Yeah if there's a lot of information then a separate page will be better

**Comment by girardinsamuel** [comment]
Here it is https://github.com/MasoniteFramework/docs/pull/168
