### ISSUE TITLE
Add back in the routes feature for the "ease of use" package feature

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#190]

**Comment by girardinsamuel** [comment]
Actually the feature is still there, we just removed the tests as we have seen that a lot of routes were registered and it was difficult to make an assertion of the routes added by the package..but I will try to fix the test still so that we can close this issue.

**Comment by josephmancuso** [comment]
Don't even waste your time on that then. We don't need tests for every single little thing. It would be nice but don't waste your time on it if it doesn't work. Spend a few minutes on it. If it doesn't work just close this issue and make sure docs are updated correctly
