### ISSUE TITLE
Add service provider docs

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#199]
I am feeling that we missed some explanations of the whole container (bind, resolve) system along with what is a service provider.
Masonite is entirely based on this and creating package for Masonite should be ideally done by creating a provider and registering it so I guess we should explain this on its own page.

In M3 we had a section ARCHITECTURAL CONCEPTS with a page `Service Providers`. 

Should we bring back this section and update it a bit ? What do you think ?

**Comment by josephmancuso** [comment]
Good point we did miss this
