### ISSUE TITLE
Add service container docs

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#217]
Need documentation again on the service container. May be able to adapt M3 documentation

**Comment by girardinsamuel** [comment]
I agree. It should be written in ARCHITECTURE section.
I guess this page https://docs.masoniteproject.com/architectural-concepts/service-container from M3 can totally be adapted/partially rewritten.

The hierarchy (sections / titles) of the page should be made easier to follow and maybe less deep

**Comment by girardinsamuel** [comment]
Actually here too much titles are at the same level
![image](https://user-images.githubusercontent.com/9897999/146802814-0c819bcd-6dff-41c0-aaa6-c145afa1f509.png)

Maybe the high level sections could be:
- Main Concepts (what is a container, theory of binding/resolving, singleton ...)
- Interacting with the container (help on using it)
- Advanced (more advanced usage of it: hooks, strict, override...)

**Comment by girardinsamuel** [comment]
Looks okay to me now. We could have a summary on the right or more hierarchy but fine for now.
