### ISSUE TITLE
Handle frontend scaffolding

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#227]
In M3 we had a `preset` command to install a frontend preset.
vue3, tailwind CSS, react, bootstrap

What should we do here ?

**Comment by josephmancuso** [comment]
We could probably just copy and paste that implementation from M3 right?

**Comment by girardinsamuel** [comment]
Yep I'll do this !
Should we keep vue 2 ?

**Comment by josephmancuso** [comment]
nope lol
