### ISSUE TITLE
Release steps

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#233]
Few things that I am thinking of for release:
- [x] merge again masonite4 into masonite 4.0
- [x] check that README is okay
- [x] make masonite repo default branch 4.0
- [x] update the link in the README to put Discord instead of Slack in masonite and cookie-cutter repo and masonite-logging
- [x] Move all issues of Masonite4 to Masonite
- [x] update requirements.txt of masonite and cookie-cutter repo
- [x] Deploy Masonite ORM 2.0
- [x] make 4.0 default version of the masonite docs
- [x] Deploy Masonite 4 version
- [x] make cookie cutter repo default branch 4.0

**Comment by josephmancuso** [comment]
done. Masonite 4 is released 🎉
