### ISSUE TITLE
Commands for file scaffolding

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#40]
Need to create commands to scaffold:

- [x] Controllers
- [x] Queue Jobs (maybe should be bound in the queue provider?)
- [x] Mailables (Maybe should be bound in the mail provider)

**Comment by girardinsamuel** [comment]
@josephmancuso 

I guess we could add some helpers as in Laravel to resolve the path of 
- views
- routes
- controllers
- seed files
- migrations files
- models
- public folder
- resources folder ?

The use would be `view_path("app.html") # == /abs/path/to/views/app.html`. This helper could fetch default location configured in Kernel. and then would create an abs path of it with appending relative path of the given file.

Now any time we need to build a path to a specific resource we could use this helper and:
- ensure no path is hard-coded 
- ensure that path building logic is not duplicated
- and that current code does what it should do and not build some paths

**Comment by girardinsamuel** [comment]
Guess I can take this one and If you have done all others, you can start it 😅
