### ISSUE TITLE
Add utilities to ease creating packages

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#79]
I started this for M3 and I would like to migrate it to M4. Two possibilities: either in M4 core or as an external package. For me it makes sense to have this into the core.

Different approachs can be used here to provide utilities to developers wanting to create a package. In this issue I am going down the road of the provider approach. This is a first draft proposal to explain how this could work with M4.
It's inspired from https://github.com/spatie/laravel-package-tools

Of course this might not be the best approach but that's a try 😅 
 
## Specifications

M4 could provide a `PackageProvider` that you can use in your packages, to easily:
- register package configuration (and publish it if you want to override it)
- register routes (and publish them if you want to override them)
- register views (and publish them if you want to override them)
- register migrations (and publish them if you want to override them)
- register tests assertions
- register assets (that the local project can find and serve => register a location.) (and publish them if you want to override them) 
- register commands

All files could be published by default under a configurable "vendor/package-name" namespace in locations defined in Kernel.py of project. So we would use what is defined in the container to build correct locations.

This is how it could look like:

```python
from masonite.providers import PackageProvider

package_root_path = "path/to/package/root"

class MyPackageProvider(PackageProvider):

    def configure(self):
        self.name("my-package")
        self.add_config("test")
        self.add_command(MyCommand())
        self.add_routes("admin", "public", tag="my-routes")
        self.add_migrations("create_my_table", "create_my_other_package_table", tag="db")
        self.add_assets(
                {
                    "package.js": "app.js",
                    "package.css": None,
                    "sub/admin.js": "admin.js",
                }
       )
       seld.add_tests_assertions(CustomTestResponse)
       self.add_command(OtherCommand(), "DemoCommand")
```

M3 `PackageProvider` code for reference https://github.com/MasoniteFramework/masonite/pull/411/files#diff-26aa7ccb08af6962c9fcb17624445040dc5fefb313ff32a4ab939e8e2c7c0ed9 that could be used to rewrite that from scratch for M4. Here the PackageProvider, call configure method behind the scenes in the register() method. And add stuff in the boot method also.

## Small details in API
- Naming of methods could also be: self.routes(), self.register_routes(),
- Each time we could add one element or several : what should be preferred ? add_commands(Command1, Command2), add_command(Command1)
- For each kind of element we want to register it's important IMO to distinguish that the element is registered and available in the project but not copied over. If we wanted to override or extend the element then we can publish it to copy it into our projects. Example: I registered some routes from an external package. Those don't appear in my route files and it's ok. I want to customize route names or more, I will publish those routes into my project. This PackageProvider should handle both: register stuff in register() and in boot() make stuff available to be published.

**Comment by josephmancuso** [comment]
Yeah i think this would be pretty simple to do

**Comment by josephmancuso** [comment]
I think one of the only ways forward is we make it really simple to make Masonite packages because the path forward needs to involve more package maintainers for Masonite

**Comment by girardinsamuel** [comment]
Yes that is why I was proposing this above because you don't have to implement/use publishing files and deal with container binding to register all assets. You just use higher level functions.
Maybe we need to adjust the API a bit but looks quite clear to me 😉

I'll make a PR proposal
