### ISSUE TITLE
Password is not hashed automatically when saved to database

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#82]
But maybe it should be done manually and it's a not bug.

```
user = User.create({..."password": "secret"})
user.password #== secret
```

I guess we should be able to hash it before storing it in database, and it should be taken care of automatically for Users ?

**Comment by josephmancuso** [comment]
This is done when using a guard in the system. We really can't do this automatically like this. Unless we add some kind of casting to the model and do something like:

```python
__casts__ = {"password": "bcrypt"}
```

Which honestly is prob not a bad cast type anyway

**Comment by girardinsamuel** [comment]
Yes I understand. So currently it's implemented in the default Auth guard system in M4 ?
Because I can see two scenarios: 
- a User register and his password needs to be hashed "automatically" into db (in the register controller method ? in the guard ?)
- a User is created "programmatically", it might be the responsibility of the developer to ensure that password is hashed before being saved into db.


If I am adding more context, in my case I have seen when working on masonite-admin. I can now create Users and password as any other fields is saved without any processing into the database. So password are saved unencrypted into database. => I am looking for a way to tell "Hey, this resource is the User model so hash password before saving" 😅 

I guess I should play a bit with M4 Auth guards to see how it behaves as I did use it yet

**Comment by josephmancuso** [comment]
Yes. The correct way would be to use the `register` method on the user class. In M4, you should inherit the `Authenticates` class

**Comment by girardinsamuel** [comment]
Yep I understand.
Would it be a bad idea to call register() method in model save method ? I mean here that : Authenticates mixin could override model creation by calling register instead.
