### ISSUE TITLE
Suggestion for Masonite 4 APIs

### ISSUE THREAD

**Issue by nicolaipre** [MasoniteFramework/masonite4#85]
I worked quite a lot with Masonite when it was at version 2.3.20 or so, since I really liked the framework. The only bad thing was that I found it quite troublesome to get it fully working for pure REST APIs, and attempts to remove folders such as `resources` and `storage` which contained templates and javascript/css etc. 

The reason I wanted to remove these folders and everything related to **Views** was because a pure REST API will never use **Views** to return any HTML-formatted code (like Laravel blades). It will only return raw JSON blobs/data. 

When reading the White Paper for Masonite 4, I noticed the following statements under [Kernel Classes](https://github.com/MasoniteFramework/masonite4#kernel-classes): 

"Kernel classes is really just a service provider that only registers things to the application class that is **crucial to making the framework work**. For example, we need to know where the config directories are, **the view directories**, controller directories, bind middleware, etc."

The view directory (similar to Laravel blades) seems to be considered a core part of the framework (which it obviously is for MVC), which makes me worried that it again will be troublesome to use Masonite for APIs (since an API should return data, NOT a **View**.)

Considering we are in 2021 and web development is going further and further in the direction of only using REST/CRUD/Graph APIs, my suggestion is to keep this in mind when developing Masonite once again from scratch. I truly believe that a clean and simple way to create APIs with Masonite will attract a lot of new users. 

Lastly, the paragraph above is not meant to be critical or negative. It is more that I really would like this project to be as good as possible, because I really believe it has the potential. 

It would be nice to see this out of the box in M4, allowing new users to create APIs with just a few commands and defining their routes exactly like its done today.

**Comment by girardinsamuel** [comment]
Hello @nicolaipre, thanks for you feedback on API features 👍

With flexibility of Masonite 4, I guess we might be able to avoid to have views folder in our project, so should be okay. 

However could you elaborate a bit on which features you imagine in Masonite 4 core regarding API capabilities ? What's your expectations ? We are in the process of designing API related features and we don't want to enforce a specific way of designing API so any feedback is welcome !

**Comment by nicolaipre** [comment]
Sure thing! I will use an example of ASP.NET Core 5 for comparison.

Currently I am testing out ASP.NET Core 5 for Web APIs. A base API can quickly be created with a single command: `dotnet new webapi`. This scaffolds a project structure containing a controller and a model. You can then structure the folders in the project to your liking since it is all within the same namespace. 

![image](https://user-images.githubusercontent.com/16032412/114204275-4abd6f80-9959-11eb-9c60-3dbe93e1af75.png)

In this example I have moved the model into a Models folder. The project structure is minimal, and consists of very few files by default. The whole framework is imported from packages.

Unfortunately the way of registering routes with ASP.NET Core is (in my opinion) a mess with verbs and decorators, and it [is not possible to register routes](https://github.com/dotnet/aspnetcore/issues/31601) the same way Masonite does route registration. 

This, and the fact that I love Masonite for being very user friendly, clean and easy to use, is why I keep coming back to Masonite every time I try a different framework...

In a perfect world, it would be amazing to see something similar to `dotnet new webapi` in Masonite 4, by adding for instance `craft new webapi` that creates a project structure similar to this:

![image](https://user-images.githubusercontent.com/16032412/114206100-47c37e80-995b-11eb-916b-5cc329ceedf1.png)

While keeping route registration the way it is today (`routes.py`):
```python
"""API Routes."""

from masonite.routes import RouteGroup
from masonite.routes import Get as GET, Post as POST

ROUTES = [
    RouteGroup(
        domain="auth",
        namespace="auth",
        routes=[
            POST('/login',    'LoginController').name('login'),
            POST('/logout',   'LogoutController').name('logout'),
            POST('/register', 'RegisterController').name('register').middleware('check_registration_status'),
            POST('/refresh',  'RefreshController').name('refresh'),
        ]
    )
]
```

I believe this should be doable without too many modifications to the core. But yeah, this is just a suggestion. By implementing this people could spin up new web APIs and get started with Masonite in less than 60 seconds. 

If you are interested in this, I am more than willing to help implement it!

**Comment by nicolaipre** [comment]
Another example is the very popular Go framework [gin](https://github.com/gin-gonic/gin). 

Example project structure and usage can be seen in this [small example project](https://github.com/eddycjy/go-gin-example).

**Comment by girardinsamuel** [comment]
Thanks for your feedback it should be definitely possible to do something like this with M4 quite easily.
@josephmancuso what's your toughts on this ?

**Comment by josephmancuso** [comment]
> The view directory (similar to Laravel blades) seems to be considered a core part of the framework (which it obviously is for MVC), which makes me worried that it again will be troublesome to use Masonite for APIs (since an API should return data, NOT a View.)

So M4 is built very differently for M3. M3 made *a lot* of assumptions. One of the assumptions is that you will have at least the ViewProvider installed. The View class would rely on some of those directories.

For M4, everything is a "feature". So the queue feature for example works exactly the same as the mail feature In terms of how its structured.

Running with this idea, even more "core" features like routing and views also work the same way. 

Also M4 relies much more heavily on the container so when the white paper says that "we need to know where the config directories are, the view directories", if you don't have the view feature installed then you wouldn't need to register the option.

For M4, by default most things will be installed. I always found it easier to remove things from a framework than add things. Removing most things be removing a service provider and done. Removing other features might be removing directories or config files.

For M4 we are making everything highly customized. So you can now determine what your project structure looks like. Changing where controllers are stored is just changing a container key in your application kernel.

**Comment by josephmancuso** [comment]
@nicolaipre I'm still working through the API stuff in a PR. 

There are some open questions i have that maybe i can get your thoughts on. Maybe i can lean on you when working through the API stuff.

1) I was thinking about only shipping READ endpoints. So things like simple mapping classes, serialization classes, authentication classes, etc. **How important is it to you that you have full Create update delete functionality?** I suppose if you have a full crud without even views then everything needs to be controlled via the API's we make available.

Most times though you have an interface on your web app and then you have an API for fetching information and then you build your own custom logic for creating things. Most times its not as simple as just posting data.

There were more questions I had but I can't remember them right now

**Comment by nicolaipre** [comment]
@josephmancuso Thank you for explaining the differences to come in M4. This sounds very promising :+1: 

Sure. I am by no means an expert on this subject, but I will do my best to contribute if that can be of help! 

The most important is getting a basic REST implementation, where I can point a route to a controller method, and get a pure JSON response in return. I am only requesting a way to support returning pure JSON responses without requiring views. 

In my case, I do not have any interfaces on my web app, I develop single page applications where I have a pure REST API backend, and a separate project containing my React/Vue.js frontend, which is communicating with the backend using REST only.

I got a little confused with `I suppose if you have a full crud without even views then everything needs to be controlled via the API's we make available.`, so sorry if I misunderstood. I have made an example below to clarify what I mean.

---

As an example, it would be amazing to see the command `craft new webapi` scaffold a base project structure like this:
![image](https://user-images.githubusercontent.com/16032412/114362155-4ff80580-9b77-11eb-8ac7-e77fd5572e24.png)

Where you for example have a route `GET('/ping',    'PingController@ping').name('ping')` that points to the PingController method Ping, which returns a JSON response:
```python
class PingController(Controller):
    """PingController Controller Class."""
    model = User

    def ping(self):
        return self.response.json({'message': 'pong'}, status=200)
```

Thats it. 

This is the essence of what I mean by not using `views`, where you can have your Javascript frontend send API requests to backend (Masonite). 

An implementation like this is very bare bones, and if I understood correctly, users could then add any Masonite 4 features they would like to use by importing them. 

Users could then create masonite packages for middleware, authentication or whatever they would like and import these to use in their web api.

**Comment by josephmancuso** [comment]
Masonite 4 at this point is ready to release. We need to make sure some documentation is updated and some articles and how-to's are available. There are some great people working on this like @hungrybluedev and @girardinsamuel.

In the meantime while those things are being worked on, I will take another attempt at getting an API feature at least to a working example and we can expand on it.

building API's and SPA's with Masonite doesn't seem like a small minority of users anymore. More and more people are building API's now and Masonite needs to have a very strong first party support for it

**Comment by josephmancuso** [comment]
Closing this as its mainly an informational issue linked in another ticket (#45)
