### ISSUE TITLE
File upload behaviour

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite4#88]
When uploading a file using `LocalDriver` class, the `store` method returns the abs path to the file, but often in database
we want to store the path relative to the project. Then it's the role of e.g. the `static` template helper to build the path to the file depending on the driver. It's also important for static file serving to work.

For now in my project when I do:
```python
path = self.application.make("storage").disk("local").store(my_file)
``` 
`path` is an absolute path. It was not the behaviour in M3

here is the path:
`'/Users/sam/masonite-admin/tests/integrations/storage/uploads/70fc8f283543e77bd4434d00d6694a1dedf89454.png`

maybe it should be only `tests/integrations/storage/uploads/70fc8f283543e77bd4434d00d6694a1dedf89454.png`
then `static` helper 
```python
static("local", "tests/integrations/storage/uploads/70fc8f283543e77bd4434d00d6694a1dedf89454.png") # == "/static/70fc8f283543e77bd4434d00d6694a1dedf89454.png"
```
and then it can be served by whitenoise if we have this config in Kernel
```python
        storage.add_storage_assets(
            {
                # folder          # template alias
                "tests/integrations/storage/static": "static/",
                "tests/integrations/storage/compiled": "static/",
                "tests/integrations/storage/uploads": "static/",
                "tests/integrations/storage/public": "/",
            }
        )
```

**Comment by girardinsamuel** [comment]
@josephmancuso  what's your opinion on this ?

**Comment by josephmancuso** [comment]
@girardinsamuel you are right. These drivers should be returning the relative paths

**Comment by girardinsamuel** [comment]
Okay I guess I can fix this, I'll open a PR 😉
